language: node_js
node_js:
  - 14
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    package:
      - postgresql-11
      - postgresql-client-11
before_script:
  - psql -c "CREATE USER docker WITH PASSWORD '123mudar' ;"
  - psql -c 'create database tests WITH OWNER = docker ;'
script:
  - eslint 'src/**'
  - yarn test:coveralls
