language: node_js
node_js:
  - 14
services:
  - postgresql
env:
  global:
    - DB_NAME=tests
    - DB_USER=docker
before_script:
  - psql -c "CREATE USER ${DB_USER} WITH PASSWORD '123mudar' ;"
  - psql -c 'create database ${DB_NAME} WITH OWNER = ${DB_USER} ;'
script:
  - eslint 'src/**'
  - yarn test:coveralls
