language: node_js
node_js:
  - 14
services:
  - postgresql
addons:
  postgresql: "11"
env:
  global:
    - DB_PORT=5432
    - DB_NAME=tests
    - DB_USERNAME=docker
    - DB_PASSWORD=123mudar
before_script:
  - psql -c 'create database ${DB_NAME};' -U postgres
  - psql -c "CREATE USER ${DB_USERNAME WITH PASSWORD ${DB_PASSWORD};" -U postgres
script:
  - eslint 'src/**'
  - yarn test:coveralls
