language: node_js
node_js:
  - 14
services:
  - postgresql
before_script:
  - psql -c 'create database tests;' -U postgres
  - psql -c "CREATE USER docker WITH PASSWORD '123mudar';" -U postgres
script:
  - eslint 'src/**'
  - yarn test:coveralls
