version: "2"
services:
  database:
    container_name: boilerplate-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB="${DB_NAME}"
      - POSTGRES_USER="${DB_USERNAME}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
